linters:
  enable-all: true
  disable:
    - testpackage
    - paralleltest
    - ireturn
    - varnamelen
    - prealloc
    - ifshort
    - nlreturn
    - depguard
    - wsl
    - interfacer
    - exhaustivestruct
    - godox
    - exhaustruct
    - godot
    - varcheck
    - nosnakecase
    - deadcode
    - golint
    - structcheck
    - maligned
    - scopelint
    - gosimple
    - lll
    - gci
    - goimports